// Mocks generated by Mockito 5.4.6 from annotations
// in posts_challenge/test/features/posts/presentation/bloc/posts_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:posts_challenge/core/error/failure.dart' as _i5;
import 'package:posts_challenge/features/posts/domain/entities/post.dart'
    as _i6;
import 'package:posts_challenge/features/posts/domain/usecases/get_posts.dart'
    as _i2;
import 'package:posts_challenge/features/posts/domain/usecases/toggle_post_like.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetPosts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPosts extends _i1.Mock implements _i2.GetPosts {
  MockGetPosts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.PostEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.PostEntity>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.PostEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.PostEntity>>>);
}

/// A class which mocks [TogglePostLike].
///
/// See the documentation for Mockito's code generation for more information.
class MockTogglePostLike extends _i1.Mock implements _i8.TogglePostLike {
  MockTogglePostLike() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> call(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [postId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#call, [postId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
