// Mocks generated by Mockito 5.4.6 from annotations
// in posts_challenge/test/features/posts/data/repositories/posts_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:posts_challenge/core/error/failure.dart' as _i5;
import 'package:posts_challenge/features/posts/data/datasources/posts_local_datasource.dart'
    as _i9;
import 'package:posts_challenge/features/posts/data/datasources/posts_remote_datasource.dart'
    as _i2;
import 'package:posts_challenge/features/posts/data/models/comment_model.dart'
    as _i8;
import 'package:posts_challenge/features/posts/data/models/post_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PostsRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsRemoteDatasource extends _i1.Mock
    implements _i2.PostsRemoteDatasource {
  MockPostsRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.PostModel>>> fetchPosts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPosts, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.PostModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.PostModel>>>(
                    this,
                    Invocation.method(#fetchPosts, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.PostModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.CommentModel>>>
  fetchCommentsByPost(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommentsByPost, [postId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i8.CommentModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i8.CommentModel>>
                  >(this, Invocation.method(#fetchCommentsByPost, [postId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.CommentModel>>>);
}

/// A class which mocks [PostsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsLocalDataSource extends _i1.Mock
    implements _i9.PostsLocalDataSource {
  MockPostsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> getLikedPostIds() =>
      (super.noSuchMethod(
            Invocation.method(#getLikedPostIds, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> saveLikedPostId(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#saveLikedPostId, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeLikedPostId(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#removeLikedPostId, [postId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
